import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import confetti from 'canvas-confetti';
import { AuditReport } from '../types/drishti';

export class ExportService {
  /**
   * Export PDF Executive Report
   */
  public static async exportPDF(report: AuditReport): Promise<void> {
    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      // Header Banner
      doc.setFillColor(35, 32, 70); // Deep Indigo
      doc.rect(0, 0, 210, 32, 'F');

      doc.setTextColor(240, 169, 59); // Amber
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('DRISHTI — Executive UX Audit Report', 14, 18);

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.text(`Site: ${report.siteName} | Target KPI: ${report.kpiGoal} | Date: ${new Date().toLocaleDateString()}`, 14, 26);

      // UX Score Box
      doc.setFillColor(245, 245, 250);
      doc.rect(14, 38, 182, 22, 'F');
      doc.setTextColor(35, 32, 70);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`UX Health Score: ${report.diagnosis.overall_score}/100`, 20, 48);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text(`Identified ${report.diagnosis.findings.length} Actionable UX Friction Points`, 20, 54);

      // Executive Summary
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text('Executive Summary:', 14, 68);

      doc.setFontSize(9.5);
      doc.setFont('helvetica', 'normal');
      const splitSummary = doc.splitTextToSize(report.diagnosis.executive_summary, 182);
      doc.text(splitSummary, 14, 75);

      // Fix First Priority
      let yOffset = 75 + splitSummary.length * 5 + 6;
      doc.setFillColor(254, 243, 199);
      doc.rect(14, yOffset, 182, 18, 'F');
      doc.setTextColor(180, 83, 9);
      doc.setFontSize(9.5);
      doc.setFont('helvetica', 'bold');
      doc.text('RECOMMENDED FIX FIRST:', 18, yOffset + 7);
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      const splitFix = doc.splitTextToSize(report.diagnosis.fix_first, 174);
      doc.text(splitFix, 18, yOffset + 13);

      // Findings List
      yOffset += 26;
      doc.setTextColor(35, 32, 70);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text('Ranked AI Findings & Empirical Evidence:', 14, yOffset);

      yOffset += 8;
      report.diagnosis.findings.slice(0, 5).forEach((finding, idx) => {
        if (yOffset > 260) {
          doc.addPage();
          yOffset = 20;
        }

        doc.setFontSize(9.5);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(finding.severity === 'Critical' ? 220 : 30, 38, 38);
        doc.text(`#${idx + 1} [${finding.severity}] ${finding.issue}`, 14, yOffset);

        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(60, 60, 60);

        const evText = doc.splitTextToSize(`• Evidence: ${finding.evidence}`, 180);
        doc.text(evText, 18, yOffset + 5);

        const recText = doc.splitTextToSize(`• Actionable Fix: ${finding.recommendation}`, 180);
        doc.text(recText, 18, yOffset + 5 + evText.length * 4);

        yOffset += 12 + (evText.length + recText.length) * 4;
      });

      // Footer Upsell Tag
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text('Generated by Drishti AI UX Engine — Install 1-line tracking snippet to validate findings live.', 14, 285);

      doc.save(`Drishti_UX_Audit_Report_${report.siteId}.pdf`);

      // Trigger Confetti Feedback
      confetti({ particleCount: 60, spread: 70, origin: { y: 0.6 } });
    } catch (err) {
      console.error('PDF Export Error:', err);
    }
  }

  /**
   * Export CSV Raw Click & Event Data
   */
  public static exportCSV(report: AuditReport): void {
    const headers = ['Click_ID', 'Device', 'Target_Selector', 'X_Pos', 'Y_Pos', 'Relative_X', 'Relative_Y', 'Timestamp'];
    const rows = report.behavior.clicks.map((clk) => [
      clk.id,
      clk.device,
      `"${clk.selector}"`,
      clk.x,
      clk.y,
      clk.relativeX,
      clk.relativeY,
      clk.timestamp
    ]);

    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `Drishti_Raw_ClickData_${report.siteId}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    confetti({ particleCount: 40, spread: 50, origin: { y: 0.6 } });
  }

  /**
   * Export JSON Structured Report
   */
  public static exportJSON(report: AuditReport): void {
    const jsonStr = JSON.stringify(report, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `Drishti_Findings_${report.siteId}.json`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    confetti({ particleCount: 40, spread: 50, origin: { y: 0.6 } });
  }
}
